### ISSUE TITLE
JumpToStep

### ISSUE THREAD

**Issue by jumpjack** [GitMoDu/FastX9CXXX#5]
Is there any known bug on JumpToStep? It makes my Arduino Leonardo freeze. Up() and Down() work fine.

**Comment by GitMoDu** [comment]
I never encountered that bug, and I have no setup to test right now.

The JumpToStep method is simple.
```
while (CurrentStep != step)
		{
			if (CurrentStep > step)
			{
				Down(false);
			}
			else
			{
				Up(false);
			}
		}
```

The only reason this is could be locking is if Up() or Down() are not doing what they're supposed to. Does it lock every time, or only if you JumpToStep(X9_STEPS)?

**Comment by GitMoDu** [comment]
Found it! There was a bug, on Down(): the CurrentStep couldn't reach 0, so the while loop on JumpToStep() never exited.
Pull the latest update (1d17580dabe4c42f06bde6aa68e96d68e9a3c96e) and it's fixed.
Thank you for your feedback.
