### ISSUE TITLE
Support for ESP32

### ISSUE THREAD

**Issue by qwksilver** [GitMoDu/FastX9CXXX#6]
Arduino: 1.8.13 (Windows 10), Board: "WiFi LoRa 32(V2), Disabled, 240MHz (WiFi/BT), 921600, None, REGION_EU868, None"
WARNING: library FastX9CXXX-master claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).

I like the simplicity of just sending the value i want and having the change happen, i would like use this, but I am a total noob at programing, so any help you are willing to give would be appreciated.

**Comment by GitMoDu** [comment]
The main branch of this library only uses Arduino digitalWrite. If you want to volunteer to test on ESP32, I'll add the support flag once it's all cleared.

All you need to do to enable the library locally for ESP32 is edit the library.properties files and replace **architectures=avr** with  **architectures=***.

**Comment by GitMoDu** [comment]
Updated in https://github.com/GitMoDu/FastX9CXXX/commit/6dc7559218efbd0b4b924955d40e7edc15c12283
Feel free to leave some feedback.

**Comment by qwksilver** [comment]
i'll let you know if i have any issues.

**Comment by qwksilver** [comment]
```
Input_display_output:120:3: error: 'Potentiometer' was not declared in this scope
   Potentiometer.Setup(X9_CS_PIN_A, X9_UD_PIN_A, X9_INC_PIN_A);
   ^
Input_display_output:129:3: error: 'Potentiometer' was not declared in this scope
   Potentiometer.Setup(X9_CS_PIN_B, X9_UD_PIN_B, X9_INC_PIN_B);
   ^
exit status 1
'Potentiometer' was not declared in this scope
```
i'm utilizing pieces from a sample file to get here, i see nothing defining potentiometer but i rather thought that was the call to the library.

**Comment by qwksilver** [comment]
ok i found what i was missing for that, but now this jumps back into a library dependency.

C:\Users\Benjamin\Documents\Arduino\libraries\Fast-master\src\Fast.cpp: In member function 'virtual bool Fast::Setup(uint8_t)':
C:\Users\Benjamin\Documents\Arduino\libraries\Fast-master\src\Fast.cpp:131:7: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'uint8_t* {aka unsigned char*}' in assignment
  Mode = portModeRegister(digitalPinToPort(pin));
       ^
C:\Users\Benjamin\Documents\Arduino\libraries\Fast-master\src\Fast.cpp:132:9: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment
  OutPin = portOutputRegister(digitalPinToPort(pin));
         ^
C:\Users\Benjamin\Documents\Arduino\libraries\Fast-master\src\Fast.cpp:133:8: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment
  InPin = portInputRegister(digitalPinToPort(pin));
        ^
exit status 1
Error compiling for board WiFi LoRa 32(V2).

**Comment by GitMoDu** [comment]
Please use the **_master_** branch, and not the **_fast_** branch. The **_fast_** branch is for AVR only. If you only use ESP32, you can remove the Fast library altogether.

**Comment by qwksilver** [comment]
oh ok, I am on the master branch, i had read somewhere that fast was needed, but taking it out did fix my compile so I should be able to write the sketch over tonight and test, thanks for the help, and i'll let you know how well it works.  For the record I am on a Heltek ESP32 with OLED.

**Comment by GitMoDu** [comment]
Yes, that was the old version made for AVR only. I have since separated that into a separate optimized branch (**_fast_**), while keeping the **_master_** slower but with full Arduino compatibility.
Do let me know if everything works, but I'll assume it is and keep the platform support as open.

**Comment by qwksilver** [comment]
ok it's moving along, but not behaving as expected, so my question is when the serial monitor reports the resistance, is that because the library read the current value and reported (confirmation) back or is the library internally keeping track of where it should be, and reporting (theoretical) back?

command.
Serial.print(Potentiometer.GetEstimatedResistance(), DEC);

i know it's estimated because materials etc, but 39 steps should be ~3900 resistance if i am reading data sheets correctly. but we're back to does the above command actually read the pot, or no?

**Comment by GitMoDu** [comment]
> ok it's moving along,

Good to hear!

> library read the current value and reported (confirmation) back or is the library internally keeping track of where it should be, and reporting (theoretical) back?


**Keeping track internally and reporting back**. That's why on startup the resistance is reset. There is no feedback from the IC, nothing to read.

Now if the returned estimated value is wrong, that's another issue.

**Comment by qwksilver** [comment]
ah, I got the idea from here, https://www.youtube.com/watch?v=OkVPjrETyno, I though he was some how reading the ic, but it looks like he is just reading the pot wiper side when I looked at the code.  Basically the trouble I get is an extremely noisy signal that doesn't appear to move up and down, I'm currently in a breadboard with the whole contraption, so I may move to a solder prototype to secure up all the connections and see where the audio instability comes from.

**Comment by GitMoDu** [comment]
You should be able to get it running with the breadboard setup. Pay attention to your pins, you have to wire it up properly, like this: https://www.electrical4u.com/potentiometer/.
I've dug out my X9C104S breakout board from the basement (haven't used them in years) and I'll do some tests, validation, maybe add some more documentation.
I also haven't given much thought to storage, just left it as an option, so you won't come into write issues like the video you shared, since you only store the value in the chip if you want. For similar use cases, I'd just move that reduced writes approach to permanent storage to the Arduino EEPROM instead (I'd add wear levelling as well, because why not) and rely instead on the internal status tracking of the FastX9CXX driver to always know where the resistance is at.

**Comment by GitMoDu** [comment]
Updated in 0189035fa91721ff07e0eff0585eb183f326d0e5.

I've verified the behaviour (on an Arduino Uno) and even added the plot I got to the readme.

**Comment by GitMoDu** [comment]
I'm marking this issue as solved.
If you find any other problems, feel free to open a new Issue.
