### ISSUE TITLE
[Feature request] An example for using multiple potentiometers

### ISSUE THREAD

**Issue by Bougakov** [GitMoDu/FastX9CXXX#7]
Hello. Thanks for a useful library. Could you please (a) confirm that it would work with more than one digital pot? (b) if yes, please add one more example on how to use them. Thanks in advance!

**Comment by GitMoDu** [comment]
Hi Bougakov.
Yes, you can definitely use more than one digital pot, provided you have enough digital pins available. Each pot uses 3 digital pins.

Excellent idea on the multi-pot example, I'll add such an example when I can.

In the meanwhile, you can just do something like this:

```
FastX9C104 Potentiometer1(X9_CS_PIN1, X9_UD_PIN1, X9_INC_PIN1);

FastX9C103 Potentiometer2(X9_CS_PIN2, X9_UD_PIN2, X9_INC_PIN2);
```

**Comment by Bougakov** [comment]
Thanks! I was considering using digital pots after I threw out not one, but three! fake "Bourns" precision pots bought on AliExpress. All of them broke just after two or three rotations. I figured out digital pots controlled by Arduino and a rotary encoder would be much more reliable.

**Comment by GitMoDu** [comment]
Yes, I don't use normal pots because they're unreliable or super expensive. Do bear in mind the Datasheet and specifications for these devices: the current through the network maxes out at a couple of mA.

**Comment by Bougakov** [comment]
Mine simply didn't have any lubricant inside. I didn't apply any serious voltage, just tested the resistance with a multimeter. The coils in the fakes are of such poor quality that they break almost instantly...

**Comment by GitMoDu** [comment]
Added in 85345f5d6fcadf7309e5c95bf3e9efc16fd33dc2.
