### ISSUE TITLE
Some Examples are not compiling

### ISSUE THREAD

**Issue by snyper0971** [GitMoDu/FastX9CXXX#8]
I am receiving the following error when attempting to compile an example in PlatformIO.

Here is the example sketch:
`#include <Arduino.h>
#include <FastX9CXXX.h>

/*
Example project to control a X9CXXX digital potentiometer

https://github.com/GitMoDu/FastX9CXXX

modified 30 Aug 2017
by MoDu
*/

#define X9_CS_PIN 3
#define X9_UD_PIN 4
#define X9_INC_PIN 5

FastX9CXXX Potentiometer;

void setup() {
	Serial.begin(9600);
	Serial.println();
	Serial.print(F("X9C104 Digital Potentiometer setup..."));
	randomSeed(analogRead(0));
	//Potentiometer.Begin();
	Potentiometer.Setup(X9_CS_PIN, X9_UD_PIN, X9_INC_PIN);
	Serial.println(F(" complete."));

}

void loop() {
	Potentiometer.JumpToStep(100);
	Serial.print(F("Potentiometer current step: "));
	Serial.print(Potentiometer.GetStep(), DEC);
	Serial.println();
	delay(1000);    // wait for a second
}`

Here is the error being returned.

`src/main.cpp:18:1: error: invalid use of template-name 'FastX9CXXX' without an argument list
 FastX9CXXX Potentiometer;
 ^~~~~~~~~~
src/main.cpp:18:1: note: class template argument deduction is only available with -std=c++1z or -std=gnu++1z
In file included from src/main.cpp:12:0:
lib/FastX9CXXX/src/FastX9CXXX.h:23:7: note: 'template<long unsigned int Resistance> class FastX9CXXX' declared here
 class FastX9CXXX
       ^~~~~~~~~~`

Any help would be appreciated

Thanks, Mitch

**Comment by snyper0971** [comment]
Ok so the WiperTest works fine. I see now that the code above we not implementing the class correctly.

**Comment by GitMoDu** [comment]
It seems like some examples haven't been updated, I'll can fix that quick.

EDIT: I'm not sure why it didn't compile before, both options for constructor and setup are available.
EDIT 2: seems likely you were using an old version. Just update to latest one.
